### ISSUE TITLE
using figcaption: "title" causes exceptions if used with markdown-it-footnote or markdown-it-abbr

### ISSUE THREAD

**Issue by kari** [arve0/markdown-it-implicit-figures#55]
Hi,

It doesn't seem to be possible to use figcaption: "title" option if using either markdown-it-footnote or markdown-it-abbr

```
import markdownIt from "markdown-it";
import markdownItAbbr from "markdown-it-abbr";
import markdownItFootnote from "markdown-it-footnote";
import markdownItImplicitFigures from "markdown-it-implicit-figures";

const md = markdownIt()
  .use(markdownItAbbr)
  .use(markdownItFootnote)
  .use(markdownItImplicitFigures, {
    figcaption: "title",
  });

const input = '![alt text](img.jpg "title text")'

console.log(md.render(input));
```

will cause exception in either footnote
```
file:///Users/kari/Code/md/node_modules/markdown-it-footnote/index.mjs:274
    if (!state.env.footnotes) { return }
                   ^

TypeError: Cannot read properties of undefined (reading 'footnotes')
    at Array.footnote_tail (file:///Users/kari/Code/md/node_modules/markdown-it-footnote/index.mjs:274:20)
    at Core.process (file:///Users/kari/Code/md/node_modules/markdown-it/lib/parser_core.mjs:56:13)
    at MarkdownIt.parseInline (file:///Users/kari/Code/md/node_modules/markdown-it/lib/index.mjs:546:13)
    at Array.implicitFigures (/Users/kari/Code/md/node_modules/markdown-it-implicit-figures/index.js:75:35)
    at Core.process (file:///Users/kari/Code/md/node_modules/markdown-it/lib/parser_core.mjs:56:13)
    at MarkdownIt.parse (file:///Users/kari/Code/md/node_modules/markdown-it/lib/index.mjs:511:13)
    at MarkdownIt.render (file:///Users/kari/Code/md/node_modules/markdown-it/lib/index.mjs:530:36)
    at file:///Users/kari/Code/md/figures-abbr-footnote.js:14:16
    at ModuleJob.run (node:internal/modules/esm/module_job:268:25)
    at async onImport.tracePromise.__proto__ (node:internal/modules/esm/loader:543:26)
```

or in abbr
```
file:///Users/kari/Code/md/node_modules/markdown-it-abbr/index.mjs:62
    if (!state.env.abbreviations) { return }
                   ^

TypeError: Cannot read properties of undefined (reading 'abbreviations')
    at Array.abbr_replace (file:///Users/kari/Code/md/node_modules/markdown-it-abbr/index.mjs:62:20)
    at Core.process (file:///Users/kari/Code/md/node_modules/markdown-it/lib/parser_core.mjs:56:13)
    at MarkdownIt.parseInline (file:///Users/kari/Code/md/node_modules/markdown-it/lib/index.mjs:546:13)
    at Array.implicitFigures (/Users/kari/Code/md/node_modules/markdown-it-implicit-figures/index.js:75:35)
    at Core.process (file:///Users/kari/Code/md/node_modules/markdown-it/lib/parser_core.mjs:56:13)
    at MarkdownIt.parse (file:///Users/kari/Code/md/node_modules/markdown-it/lib/index.mjs:511:13)
    at MarkdownIt.render (file:///Users/kari/Code/md/node_modules/markdown-it/lib/index.mjs:530:36)
    at file:///Users/kari/Code/md/figures-abbr-footnote.js:14:16
    at ModuleJob.run (node:internal/modules/esm/module_job:268:25)
    at async onImport.tracePromise.__proto__ (node:internal/modules/esm/loader:543:26)
```

**Comment by kari** [comment]
After some investigation, this seems to happen because `md.parseInline(figCaption)` sends an empty environment and these plugin expect their keys to exist. This outright crashing can be solved by just changing the call to `md.parseInline(figCaption, state.env)`.

However, this doesn't fully solve compatibility issues with these two plugins:

- If the figCaption uses abbreviations, these will be processed twice and the abbreviation will be nested in two `<abbr>`s. This can be solved by disabling `markdown-it-abbr` before calling `md.parseInline` (and re-enabling afterwards). (One could argue this is a bug in `markdown-it-abbr`)
- if the figCaption uses footnotes, these will not be included in footnotes. This is because [`markdown-it-footnote`'s core rule `footnote_tail` is before `markdown-it-implicit-figures` in rule orders](https://github.com/markdown-it/markdown-it-footnote/blob/fe6c169c72b9f4d6656b10aa449128456f5a990e/index.mjs#L352). This can be partially solved by first ensuring `markdown-it-implicit-figures` is `use`d after `markdown-it-footer` and checking whether `footnote_tail` exist in core rules and if so, `ruler.before` `markdown-it-implicit-figures` before it (instead of `linkify`). I don't know how to address this issue if the `use` order is reversed. 

The obvious workaround is not to use these markups within an image's `alt` or `title`. In this case, just providing the `state.env` in `md.parseInline` should be enough.
